= FollowOCPN
:table-caption!:

== What this script addresses

This script sends navigational and route data out over one or more NMEA0183 ports, thus making it available to other systems.

OpenCPN has built-in support for many autopilots but if your autopilot or other system is not supported, this script could be the way to add support for your device.
If it does not do exactly what you need, it can be easily modified to suite your requirements.

For devices running iNavX, it transfers the OpenCPN active route to iNavX and activates it.  Any updates to the route are updated in the iNavX app.

This script replaces my earlier SendActiveRoute script.

== Installing the script

This script needs JavaScript plugin v3.1 or later.

1. Copy this URL to your clipboard (copy link - do not follow it) `https://raw.githubusercontent.com/antipole2/FollowOCPN/main/followOCPN.js`
2. In a JavaScript console choose `Load` and then `URL on clipboard`.  The script should be loaded into the script pane.
3. Choose `Run` to start the script.

If you want to run the script when not online, you will need to save it to a local file.  You can tick the _Auto run_ box to have the script start automatically.

Alternatively, you can fork the repository if you want to evolve the script.

== What the script does
