= FollowOCPN

:icons: image
:iconsdir: ..

== What this script does

This script sends navigational and route data out over one or more NMEA0183 ports, thus making it available to other systems.

OpenCPN has built-in support for many autopilots but if your autopilot or other system is not supported, this script could be the way to add support for your device.
If it does not do exactly what you need, it can be easily modified to suite your requirements.

For devices running iNavX, it transfers the OpenCPN active route to iNavX and activates it.  Any updates to the route are updated in the iNavX app.

This script replaces my earlier SendActiveRoute script.

=== At a chosen interval the script sends

[horizontal]
$  GLL::  
$  VTG::  
$  HDG:: Omitted if stationary
$  RMC::  
$  MWV:: If wind data available
$  RMB:: If there is an active waypoint, it also sends
$  BOD::  

=== At a different chosen interval it sends

[horizontal]
$  WPL:: for each waypoint in the route
$  RTE:: as many sentences as required to define the route by linking the waypoints
 
NOTE: If the first waypoint in the route has not been reached, the script prepends a leg from the point of activation `Start` to the first waypoint

NOTE: OpenCPN does not require waypoint names to be unique.  If a route were constructed with the same waypoint name used for different points, it would be ambigious.  The script therefore ensures waypoint names within a route are unique.


== Installing the script

This script needs JavaScript plugin v3.1 or later.

1. Copy this URL to your clipboard (copy link - do not follow it) `https://raw.githubusercontent.com/antipole2/FollowOCPN/main/followOCPN.js`
2. In a JavaScript console choose `Load` and then `URL on clipboard`.  The script should be loaded into the script pane.
3. Choose `Run` to start the script.

If you want to run the script when not online, you will need to save it to a local file.  You can tick the _Auto run_ box to have the script start automatically.

Alternatively, you can fork the repository if you want to evolve the script.

== Support

The script can be discussed in the Discussion forum above.

Issues can be reported using the Issues tab.
