= Working with iNavX

== What this script addresses

Running a tablet or phone as a repeater for OpenCPN is unsatisfactory.
Viewing OpenCPN on such a small screen gives a poor experience.
Further, if OpenCPN were to fail, the repeater would also fail.
There is no resilience.

There are navigational applications better optimised for these devices and more robust.
One is https://inavx.com[iNavX], which is available on iOS (iPad and iPhone) and Android devices.

If OpenCPN is being used as the main planning tool and navigational application,
iNavX needs to shadow OpenCPN and keep synchronised with any changes in the navigation.

This document details how to make iNavX shadow OpenCPN using the FollowOCPN script.

The script causes iNavX to adopt any active waypoint or route.
As you advance along the route, iNavX will also advance.
If you amend the route by adding or moving route points, iNavX will update accordingly.

In the event that OpenCPN were to fail, iNavX will continue to navigate from its own ship's navigational feed.
If that feed were to fail, a device with its own GPS receiver would switch to using that.
This provided important resilience.

== Instructions for making this work

For this to work, your device running iNavX needs to receive NMEA data over a WiFi connection via a WiFi router.

Note that many instrument WiFi gateways create their own WiFi network and are not actual routers.
This is the case, for example, for the Actisense W2K-1 and also the Yacht Devices YDNR-02N.

If your gateway is not also a router, you need a WiFi router and need to connect your gateway as a client of that network.
You could use a 12V-powered WiFI router (readily available) or your computer may be able to provide this.
MacOS can create an _ad hoc_ WiFi network from the WiFi pull-down menu - in Monterey and later, this is hidden unless you enable it in Settings->Network->WiFi->Advanced and tick _Show legacy networks and options_.

. Have OpenCPN receive NMEA data from your gateway on one port - say 60001
. Have OpenCPN send NMEA data on a different port - say 60002 +
Drop outgoing sentences ECRMB,ECAPB because the script sends modified sentences NVRMB,NVAPB
. Connect your device to the same WiFi network
. Within iNavX select Instruments  > TCP/IP and set the protocol and port number to as in Step 2 above.
. On the same panel, enable Waypoints and enable Link. +
You should now see the NMEA sentences scrolling in the monitoring pane of this panel.
. Click Done and then select the Chart.

The device should now follow the ship's navigation using the ship's navigation data.

When a waypoint becomes active in OpenCPN, it becomes active in iNavX.

When a route is activated in OpenCPN, it appears as the active route in iNavX.
As OpenCPN advances the routepoint, so iNavX advances its active routepoint.
Progress along the route is available in the route tab of the ribbon at the top of the iNavX screen,
together with predicted time on route and ETA.

If you wish to force an advance to the next routepoint, this should be done on OpenCPN, whereupon iNavX will update too.

If you advance the routepoint in iNavX, it will start ignoring changes in the active route point sent from OpenCPN.
To restore this, go to the panel used for step 5 above, turn Enable Waypoints off and back on again. at home

=== Familiarisation at home

You can exercise the set-up and familiarise yourself with it while away from your boat at home.

• Set up OpenCPN as above
• Activate a route or waypoint
• Connect your iNavX device to the same WiFi network
• Determine the IP address of your computer.  On MacOS, System Preferences > Network > WiFi > Advanced > TCP/IP.
• Use this address in iNavX in the instructions above

You can drive the ship using a simulator.
Using the JavaScript plugin, open an additional console via the Tools button.
Load the driver.js script into this console and run it.
You can, for example, set a compass course and speed.

See the Driver https://github.com/antipole2/JavaScripts-shared/blob/main/Driver/Driver.adoc[instructions here.]

== My network set up

On Antipole I have an NMEA2000 network and an Actisense W2K-1 NMEA2000 to WiFi converter.
The W2K-1 is usually used to create a WiFi network.
However, it is not a router and you cannot use it to connect OpenCPN and other devices.

I happen to have a USB-powered mini-hub that British Telecom gave me when we were moving house.
This does contain a router.
So I connect the W2K-1 in client mode to the minihub and use this to provide the WiFi network.
OpenCPN receives the NMEA data from the W2K-1 on port 60001
and sends NMEA data on port 60002.
Other devices receive via port 60002.

In the event that OpenCPN were to fail, I would connect the iOS devices via port 60001 and they would receive the navigational data directly, without it being procesed via OpenCPN.
